#!/bin/bash

git pull

export NODE_OPTIONS="--max-old-space-size=4096"

npx yarn
NODE_ENV=production npx yarn build
if [ "$1" = '--migrate' ]; then
	npx yarn migrate
fi
systemctl restart gp
sleep 7
systemctl restart nginx
